export const PHYSICS = {
  // Leistungsparameter
  MAX_THERMAL_POWER: 3200,
  NOMINAL_POWER: 3200,
  TEST_POWER_MIN: 700,
  TEST_POWER_MAX: 1000,
  TEST_DURATION_SECONDS: 480,

  // Steuerstäbe
  MAX_CONTROL_RODS: 211,
  MINIMUM_SAFE_RODS: 15,
  RODS_PER_POWER_PERCENT: 2.11,

  // Xenon
  XENON_BUILD_DELAY: 30,
  XENON_DECAY_RATE: 0.002,
  XENON_BUILD_RATE: 0.004,
  XENON_MAX_REACTIVITY_PENALTY: 0.35,

  // Kühlmittel
  COOLANT_TEMP_NOMINAL: 270,
  COOLANT_TEMP_BOILING: 284,
  COOLANT_FLOW_NOMINAL: 7000,
  COOLANT_FLOW_PER_PUMP: 875,

  // Temperaturgrenzen
  FUEL_TEMP_NOMINAL: 650,
  FUEL_TEMP_WARNING: 1200,
  FUEL_TEMP_MELTDOWN: 2800,
  CORE_TEMP_WARNING: 350,
  CORE_TEMP_CRITICAL: 500,

  // Druck
  STEAM_PRESSURE_NOMINAL: 65,
  STEAM_PRESSURE_WARNING: 80,
  STEAM_PRESSURE_CRITICAL: 95,

  // Positiver Dampfblasenkoeffizient (RBMK-Konstruktionsfehler)
  VOID_COEFFICIENT: 0.0015,

  // AZ-5 Graphit-Spitzen-Effekt
  AZ5_GRAPHIT_SPIKE_DURATION: 3,
  AZ5_GRAPHIT_POWER_MULTIPLIER: 2.5,

  // Score
  BASE_SCORE: 10000,
  SCORE_PENALTY_PER_SECOND_OFF_TARGET: 5,
  SCORE_PENALTY_PER_ALARM: 200,
  SCORE_BONUS_TEST_SUCCESS: 3000,
  SCORE_BONUS_ECCS_DISABLED: 500,

  // Tick-Rate
  TICK_INTERVAL_MS: 500,
};
